stages:
  titanic_data:
    cmd: 
    - kaggle competitions download -c titanic -f train.csv
    - kaggle competitions download -c titanic -f test.csv
    outs:
    - train.csv
    - test.csv
  prepare:
    cmd: python code/prepare.py
    deps:
    - data/test.csv
    - data/train.csv
    outs:
    - data/test_prepared.pkl
    - data/train_prepared.pkl
  train:
    cmd: python code/train.py
    deps:
    - code/train.py
    - data/test_prepared.pkl
    - data/train_prepared.pkl
    metrics:
    - metrics/metrics.json
    outs:
    - models/bestModel.joblib
  inference:
    cmd: python code/inference.py
    deps:
    - code/inference.py
    - models/bestModel.joblib
    - data/test_prepared.pkl
    outs:
    - inference/predictions.csv