name: ML Pipeline
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    environment: KAGGLE
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Execute DVC Repro
        run: |
          dvc repro
          echo "### Results" >> report.md
          dvc metrics show --show-md main >> report.md
          cml publish --md >> report.md
          cml-send-comment report.md
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

